import Footer from '@/components/Footer';
import Header from '@/components/Header';
import BeforeAfterSlider from '@/components/sections/BeforeAfterSlider';
import CTASection from '@/components/sections/CTASection';
import ClubPricingLevels from '@/components/sections/ClubPricingLevels';
import FiveLiesSection from '@/components/sections/FiveLiesSection';
import HeroSection from '@/components/sections/HeroSection';
import PainPointSection from '@/components/sections/PainPointSection';
import ProGradePrecisionSection from '@/components/sections/ProGradePrecisionSection';
import SocialLinksSection from '@/components/section
